Post:
  properties:
    title:
      - NotBlank: ~
      - Length:
          min: 5
          max: 30
    content:
      - NotBlank: ~
User:
  properties:
    username:
      - NotBlank: ~
      - Length:
          min: 4
          max: 20
      - Regex:
          pattern: /[[:alnum:]]+/
          message: It should be included only letters and numbers
    password:
      - NotBlank: ~
Product:
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 3
          max: 30
Category:
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 1
          max: 30
      - Regex:
          pattern: '/\s/'
          match: false
          message: The name can not contain a space